In [2]:
import numpy as np

## ToDO
- Read and understand the first 25 Exercises from 101 NumPy Exercises
- https://www.machinelearningplus.com/python/101-numpy-exercises-python/
- Send my any sloppy prove of a few solves ;-)

In [14]:
#1
np.__version__

'1.18.1'

In [15]:
#2
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#3
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
#4
x = np.array(list(range(10)))
np.array([odd for odd in x if odd % 2])

array([1, 3, 5, 7, 9])

In [21]:
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

In [23]:
#5
x[x % 2 == 1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
#6
x = np.arange(10)
out = np.where(x % 2 == 1, -1, x)
print(out)
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [30]:
#7
x = np.arange(10)
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
#8
x = np.arange(10).reshape(2,-1)
y = np.repeat(1, 10).reshape(2,-1)
np.concatenate([x, y], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
#9
x = np.arange(10).reshape(2,-1)
y = np.repeat(1, 10).reshape(2,-1)
np.concatenate([x, y], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [37]:
#10
np.r_[np.repeat(np.array([1,2,3]), 3), np.tile(np.array([4,5,6]), 4)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6])

In [41]:
#11
x = np.arange(7)
y = np.arange(5, 10)
np.intersect1d(x, y)

array([5, 6])

In [42]:
#12
x = np.arange(1, 7)
y = np.arange(5, 10)
np.setdiff1d(x,y)

array([1, 2, 3, 4])

In [44]:
#13
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(x == y)

(array([1, 3, 5, 7]),)

In [49]:
#14
x = (np.arange(10))*3
print(x)
x[(x >= 5) & (x <= 10)]

[ 0  3  6  9 12 15 18 21 24 27]


array([6, 9])

In [51]:
#15
def bigN(x, y):
    """Return biggest number"""
    if x >= y:
        return x
    else:
        return y

out = np.vectorize(bigN, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

out(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [52]:
#16
x = np.arange(9).reshape(3,3)
x[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [53]:
#17
x = np.arange(9).reshape(3,3)
x[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [55]:
#18
x = np.arange(9).reshape(3,3)
x[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [56]:
#19
x = np.arange(9).reshape(3,3)
x[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [58]:
#20
np.random.uniform(5,10, size=(5,3))

array([[9.89469807, 7.21262143, 8.52818191],
       [7.71196485, 7.84736915, 5.19399109],
       [9.32405233, 6.39168412, 5.41862157],
       [5.67565055, 6.16099138, 6.77083825],
       [5.82069359, 9.27476628, 8.61972617]])

In [59]:
#21
x = np.random.random([5,3])
np.set_printoptions(precision=3)
x

array([[0.926, 0.198, 0.735],
       [0.569, 0.086, 0.455],
       [0.802, 0.964, 0.364],
       [0.386, 0.972, 0.545],
       [0.946, 0.915, 0.035]])

In [62]:
#22
np.random.seed(23)
np.set_printoptions(suppress=False)
np.random.random([3,3])/1e3

array([[0.001, 0.001, 0.001],
       [0.   , 0.   , 0.001],
       [0.   , 0.   , 0.001]])

In [63]:
#23
np.set_printoptions(threshold=6)
np.arange(15)

array([ 0,  1,  2, ..., 12, 13, 14])

In [67]:
#24
np.set_printoptions(threshold=1000)
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
#25
src = "countries.csv"
data = np.genfromtxt(src, delimiter=",", dtype='object')

In [73]:
data

array([[b'Name', b'People', b'Area', b'BIP', b'Currency'],
       [b'Germany', b'82521653', b'357385', b'3466', b'EUR'],
       [b'Japan', b'126045000', b'377835', b'4938', b'YEN'],
       [b'Canada', b'36503097', b'9984670', b'1529', b'CAD'],
       [b'Italy', b'60501718', b'301338', b'1850', b'EUR'],
       [b'Brazilia', b'208360000', b'8515770', b'1798', b'REAL']],
      dtype=object)